language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
- pip install poetry
# command to install dependencies
install:
- poetry install
# command to run tests
script:  
- poetry run pytest
before_deploy:
- bump2version patch
- poetry version patch
- poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true